// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type KeyBoard struct {
	ID           string  `json:"id"`
	KeyCount     int32   `json:"keyCount"`
	IsSplit      bool    `json:"isSplit"`
	Maker        string  `json:"maker"`
	HomePageLink string  `json:"homePageLink"`
	Image        *string `json:"image,omitempty"`
}

type Mutation struct {
}

type NewKeyBoard struct {
	ID           string  `json:"id"`
	KeyCount     int32   `json:"keyCount"`
	IsSplit      bool    `json:"isSplit"`
	Maker        string  `json:"maker"`
	HomePageLink string  `json:"homePageLink"`
	Image        *string `json:"image,omitempty"`
}

type Query struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
